language: objective-c
osx_image: xcode9.2

branches:
  only:
    - master
    - dev

podfile: Podfile
before_install:
  - pod install

script:
  - xcodebuild test -workspace ARMonitoring.xcworkspace -scheme ARMonitoring -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
