language: objective-c

branches:
  only:
    - master
    - dev

osx_image: xcode9.2
podfile: Podfile
script:
    - pod install xcodebuild clean test -project ARMonitoring.XCWorkspace -scheme ARMonitoring -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
