language: objective-c
osx_image: xcode9.2

branches:
  only:
    - master
    - dev

podfile: Podfile
before_install:
  - sudo gem install cocoapods
  - pod install --repo-update
  # Pre-start simulators
  - npm install ios-sim -g
  # Pre-start iPhone 7 + iOS 10.2 simulator
  - ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-7, 11.2"

script:
  - xcodebuild test -workspace ARMonitoring.xcworkspace -scheme ARMonitoring -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
